leftnav:
- identifier: 87e218ac-cd9e-20c9-12f2-f74132078c23
  name: 'Part 1: Fundamentals of Materials Structure'
  url: /pages/syllabus
  weight: 10
- identifier: external-88f59e296ffd42d288172baea8e0aca6
  name: 'Part 1: Fundamentals of Materials Structure'
  url: https://openlearninglibrary.mit.edu/courses/course-v1:MITx+3.012S.1x+1T2019/about
  weight: 1000
- identifier: external-78b1915d2c534e9694b7dc6a7c8d6587
  name: 'Part 2: The Crystalline State'
  url: https://openlearninglibrary.mit.edu/courses/course-v1:MITx+3.012S.2x+1T2019/about
  weight: 1010
- identifier: external-28df14eaff3d4a26ab1a65ca13a55556
  name: 'Part 3: Liquid Crystals, Defects, and Diffusion'
  url: https://openlearninglibrary.mit.edu/courses/course-v1:MITx+3.012S.3x+1T2019/about
  weight: 1020
